# Пример Helm релиза, который будет удален перед удалением неймспейса
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-app-config
  namespace: app-with-helm
data:
  app.properties: |
    database.url=jdbc:postgresql://db:5432/app
    app.name=Example App
    app.version=1.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: app-with-helm
  labels:
    app: example-app
    chart: example-app-1.0.0
    release: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        - name: CONFIG_MAP_NAME
          valueFrom:
            configMapKeyRef:
              name: example-app-config
              key: app.properties
